//You have almost certainly encountered certain situations,
//where a class owns some resources that must not be copied for technical reasons
class descriptor_owner {
    void* descriptor_;

public:
    explicit descriptor_owner(const char* params);

    ~descriptor_owner() {
        // system_api_free_descriptor(descriptor_);
    }
};

descriptor_owner::descriptor_owner(const char* ){}

//The C++ compiler in the preceding example generates a copy constructor
//and an assignment operator, so the potential user of the descriptor_owner class
//will be able to create the following awful things
void foo() {
    descriptor_owner d1("O_o");
    descriptor_owner d2("^_^");

    // descriptor_ of d2 was not correctly freed
    d2 = d1;

    // destructor of d2 will free the descriptor
    // destructor of d1 will try to free already freed descriptor
}

#include <boost/noncopyable.hpp>

//If you derive your own class from it,
//the copy constructor and assignment operator won't be generated by the C++ compiler
class descriptor_owner_fixed : private boost::noncopyable {
    // ...
public:
    descriptor_owner_fixed(const char* params){ (void)params; }
};

void foo2() {
    descriptor_owner_fixed d1("O_o");
    descriptor_owner_fixed d2("^_^");

    // Won't compile
    //d2 = d1;
    //descriptor_owner_fixed d3(d1);
}

struct noncopyable_or_not {
private:
    noncopyable_or_not(const noncopyable_or_not&);
    noncopyable_or_not& operator=(const noncopyable_or_not&);

public:
    noncopyable_or_not(){}
    noncopyable_or_not(noncopyable_or_not&){}
    noncopyable_or_not& operator=(noncopyable_or_not&){ return *this; }
};

struct noncopyable_or_not2 {
private:
    noncopyable_or_not2(noncopyable_or_not2&);
    noncopyable_or_not2& operator=(noncopyable_or_not2&);

public:
    noncopyable_or_not2(){}
    noncopyable_or_not2(const noncopyable_or_not2&){}
    noncopyable_or_not2& operator=(const noncopyable_or_not2&) { return *this; }
};

int main()
{
    foo();
    foo2();

    noncopyable_or_not non1;
    noncopyable_or_not non2 = non1;

    const noncopyable_or_not2 n1;
    noncopyable_or_not2 n2 = n1;

    // Supressing warnings about unused variables
    (void)non2;
    (void) n2;

    return 0;
}

